metadata:
  game_name: My Game
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2026-01-12 19:44:40'
  path: C:\Program Files\Adobe\Adobe Photoshop 2026\Photoshop.exe
  benchmark_duration: 120
  startup_wait: 30
  resolution: 1920x1080
  preset: High
  graphics_api: DirectX 11
steps:
  1:
    description: Open Dialog box
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: hotkey
      keys:
      - ctrl
      - o
    expected_delay: 2
    timeout: 20
  2:
    description: Select the file
    find:
      type: icon
      text: ColorizePhoto_Demo.jpeg
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  3:
    description: click on open button
    find:
      type: icon
      text: Open
      text_match: exact
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  4:
    description: Open Filters Menu
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: hotkey
      keys:
      - alt
      - t
    expected_delay: 2
    timeout: 20
  5:
    description: Select Neural Filters option
    find:
      type: icon
      text: Neural Filters...
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  6:
    description: Click on colorize option
    find:
      type: icon
      text: Colorize
      text_match: exact
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  7:
    description: click toggle
    find:
      type: icon
      text: Mocanos
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  8:
    description: Click on Okay button
    find:
      type: icon
      text: OK
      text_match: exact
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
