metadata:
  game_name: My Game
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2026-01-12 19:17:04'
  path: C:\Program Files\Adobe\Adobe Photoshop 2026\Photoshop.exe
  benchmark_duration: 120
  startup_wait: 30
  resolution: 1920x1080
  preset: High
  graphics_api: DirectX 11
steps:
  1:
    description: Open the Open Dialog box
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: hotkey
      keys:
      - ctrl
      - o
    expected_delay: 2
    timeout: 20
  2:
    description: Select file
    find:
      type: icon
      text: QuickSelect.jpg
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  3:
    description: Click on Open Icon
    find:
      type: icon
      text: Open
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  4:
    description: Select Quick Selection Tool
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: hotkey
      keys:
      - shift
      - w
    expected_delay: 2
    timeout: 20
  5:
    description: Press on Select Subject button
    find:
      type: icon
      text: Select Subject
      text_match: exact
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 6
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
