metadata:
  game_name: Cyberpunk2077
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2025-11-18 01:07:32'
  path: C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\Cyberpunk2077.exe
  process_id: Cyberpunk 2077
  process_name: Cyberpunk 2077
  benchmark_name: Cyberpunk ingame benchmark
  benchmark_duration: 100
  startup_wait: 80
  resolution: 1920x1080
  preset: High
  engine: Red Engine 4.0
  graphics_api: DirectX 11
steps:
  1:
    description: PRESS SPACE TO CONTINUE
    find:
      type: any
      text: PRESS  TO CONTINUE
      text_match: contains
    action:
      type: key
      key: space
    verify_success:
    - type: any
      text: SETTINGS
      text_match: contains
    expected_delay: 3
    timeout: 20
  2:
    description: CLICK ON SETTINGS
    find:
      type: icon
      text: SETTINGS
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 3
    timeout: 20
  3:
    description: NAVIGATE TO GRAPHICS
    find:
      type: any
      text: DEFAULTS
      text_match: contains
    action:
      type: key
      key: '3'
    expected_delay: 2
    timeout: 20
  4:
    description: NAVIGATE TO GRAPHICS
    find:
      type: any
      text: DEFAULTS
      text_match: contains
    action:
      type: key
      key: '3'
    expected_delay: 2
    timeout: 20
  5:
    description: NAVIGATE TO GRAPHICS
    find:
      type: any
      text: DEFAULTS
      text_match: contains
    action:
      type: key
      key: '3'
    verify_success:
    - type: any
      text: BENCHMARK
      text_match: contains
    expected_delay: 2
    timeout: 20
  6:
    description: START BENCHMARK
    find:
      type: any
      text: DEFAULTS
      text_match: contains
    action:
      type: key
      key: b
    verify_success:
    - type: any
      text: CONFIRM
      text_match: contains
    expected_delay: 2
    timeout: 20
  7:
    description: HIT CONFIRM
    find:
      type: any
      text: CONFIRM
      text_match: contains
    action:
      type: key
      key: enter
    expected_delay: 2
    timeout: 20
  8:
    description: WAIT FOR BENCHMARK TO COMPLETE
    action:
      type: wait
      duration: 120
    expected_delay: 2
    timeout: 20
  9:
    description: EXIT TO MAIN MENU
    find:
      type: any
      text: Main Menu
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    verify_success:
    - type: any
      text: CONFIRM
      text_match: contains
    expected_delay: 2
    timeout: 20
  10:
    description: CONFIRM TO EXIT TO MAIN MENU
    find:
      type: any
      text: CONFIRM
      text_match: contains
    action:
      type: key
      key: enter
    expected_delay: 20
    timeout: 20
  11:
    description: PRESS SPACE TO CONTINUE
    find:
      type: any
      text: PRESS  TO CONTINUE
      text_match: contains
    action:
      type: key
      key: space
    verify_success:
    - type: any
      text: SETTINGS
      text_match: contains
    expected_delay: 3
    timeout: 20
  12:
    description: QUIT GAME
    find:
      type: any
      text: QUIT GAME
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
