metadata:
  game_name: Hitman 3 Free Starter Pack
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2025-11-08 02:03:18'
  path: '1847520'
  process_id: Launcher
  process_name: HITMAN3
  benchmark_name: Built-in Benchmark - Dubai
  benchmark_duration: 180
  startup_wait: 15
  resolution: 1920x1080
  preset: Ultra
  engine: Glacier 2
  graphics_api: DirectX 12
steps:
  1:
    description: OPEN OPTIONS MENU
    find:
      type: any
      text: sports
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 10
    timeout: 20
  2:
    description: SCROLL DOWN TO BENCHMARK OPTION
    find:
      type: any
      text: Ray Tracing
      text_match: contains
    action:
      type: scroll
      direction: down
      clicks: 3
    verify_success:
    - type: any
      text: Start Benchmark with current
      text_match: contains
    expected_delay: 6
    timeout: 20
  3:
    description: START BENCHMARK
    find:
      type: any
      text: Start Benchmark
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  4:
    description: WAIT
    action:
      type: wait
      duration: 150
    expected_delay: 2
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
