metadata:
  game_name: Tiny Tina Wonderlands
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2025-11-02 01:34:47'
  path: C:\Program Files (x86)\Steam\steamapps\common\Tiny Tina's Wonderlands\OakGame\Binaries\Win64\Wonderlands.exe
  process_name: Wonderlands.exe
  process_id: Wonderlands.exe
  benchmark_name: built in benchmark
  benchmark_duration: 120
  startup_wait: 100
  resolution: 1920x1080
  preset: High
  engine: UE4
  graphics_api: DirectX 11
steps:
  1:
    description: CLICK ON OPTIONS
    find:
      type: any
      text: OPTIONS
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 3
    timeout: 20
  2:
    description: CLICK ON BENCHMARK MENU [TENT]
    find:
      type: any
      text: Tent
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.4
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  3:
    description: CLICK ON START BENCHMARK
    find:
      type: any
      text: Start Benchmark
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.4
      click_delay: 0.2
    expected_delay: 3
    timeout: 20
  4:
    description: WAIT FOR BENCHMARK TO COMPLETE
    action:
      type: wait
      duration: 130
    expected_delay: 2
    timeout: 20
  5:
    description: CLICK ON OPTIONS
    find:
      type: any
      text: OPTIONS
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 3
    timeout: 20
  6:
    description: CLICK ON BENCHMARK MENU [TENT]
    find:
      type: any
      text: Tent
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.4
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  7:
    description: ESCAPE BACK TO MAIN MENU
    find:
      type: any
      text: Reset to Defaults
      text_match: contains
    action:
      type: key
      key: escape
    expected_delay: 3
    timeout: 20
  8:
    description: CLICK ON EXIT
    find:
      type: any
      text: EXIT GAME
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
  9:
    description: CLICK ON QUIT TO DESKTOP - CONFIRM QUIT
    find:
      type: any
      text: Quit to Desktop
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 2
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
